### ISSUE TITLE
Main odoo directory is not a git repo

### ISSUE THREAD

**Issue by DocCyblade** [l-arnold/tkl-nomadic-odoo#27] opened 2015-09-09 00:05 UTC
Looks like the move from tmp is not keeping the .git folder. may need to change how we move or copy the files or move the config files instead

**Comment by JedMeister** [comment] 2015-09-09 01:18
Just made a post that IMO is relevant here:
https://github.com/l-arnold/tkl-nomadic-odoo/issues/11#issuecomment-138744842

> You could overlay the config file still but somewhere else then mv it in in the conf (instead of mving the whole git repo).
> 
> Another (perhaps nicer IMO) idea would be to overlay the config to ./etc (e.g. /etc/odoo/odoo.conf or whatever) and then symlink to it in the odoo dir (in the conf script).
> 
> Actually IIRC it's the odoo initscript that applies the config to odoo (when it's started) so in that case you wouldn't even need to symlink - just adjust the path to point to the config file's (new) location (in /etc)

**Comment by l-arnold** [comment] 2015-09-09 01:49
Important that All Start Scripts find the Config File as well.
I would vote for keeping it in position.  In every event I know we can work through this.
Addons Are moving GIT through build but they are not undergoing the Move Process.

I think it should just be a "code dialog".  Seems "mv temp-direct odoo-direct" should work if the Config files are not overwritten, or if they are, just overwrite them again.

**Comment by l-arnold** [comment] 2015-09-10 19:30
@DocCyblade   How are we looking on this?  I have got travels coming tomorrow and would love to "do a wrap".  If time is tight, I could make a branch and try some changes so we get the Git.  (not dev-wip1).

Dev-wip1 moving along.  Should have something quite shortly that is building clean through. (just not the git transfer subject)

**Comment by DocCyblade** [comment] 2015-09-10 20:30
The issue is with the config files

De we need both config files? If not move the main config to /etc then we can do a hit clone and no move of files. If your ok with that I'll do that when I get home. Working later tonight. I'll be home 5pm your time, I can do that tonight 

Sorry have not responded, work has been busy!

**Comment by l-arnold** [comment] 2015-09-10 21:30
Hi @DocCyblade 

(EDIT:  Git is STILL Apllied to the Odoo Directory)

I just went and looked at a Running System from before the MV changes that were done a week or so ago.  In that version Git is STILL Applied to the Odoo Directory.  Code should be as is in this Directory for the MOVE PART (original Master)
https://github.com/l-arnold/tkl-nomadic-odoo/blob/master/conf.d/30_odoo_installation

Lines 31: 37
echo "--------------"
echo " Install Odoo "
echo "--------------"
git clone https://github.com/odoo/odoo.git $ODOO_DIR
chown -R openerp:openerp $ODOO_DIR
mv $ODOO_DIR_TMP/\* $ODOO_DIR
rm -rf $ODOO_DIR_TMP

I think we can move toi ETC.  I like the idea but it also seems somewhat difficult to be sure all the components get covered.

I had an outline of what we needed to cover but I then thought of looking "back" to see if Git was in those versions.  It is.

If we do want to change I can work on an outline of Pointers that need to be covered.

**Comment by l-arnold** [comment] 2015-09-10 21:36
Original Line has a \* in the first part  (meaning it pulls git subdirectory)
mv $ODOO_DIR_TMP/\* $ODOO_DIR
rm -rf /tmp/odoo_tmp

Current Line has a \* in the second part (meaning to me, I am not sure, but not taking git with it)  (also notice below: temp in line one and tmp in line 2 ??)
(Current Code 30_Main)

mv -n -t $ODOO_DIR /tmp/odoo_temp/*
rm -rf /tmp/odoo_tmp

Ultimately it should work, and ideally work best with TKL Conventions.  If that means having Conf in ETC lets do that.

**Comment by l-arnold** [comment] 2015-09-11 20:12
Ok,  So I am trying a "update" in dev-wip1  that is based on the symlink for openerp.init which is also there.
It is running the build now.

Looking ahead it looks like I made 3 x inadvertent commits to "dev".  I tried a Revert but didn't seem to have an effect.  Some of those commits I would like to keep (docs).  Mainly tried to remove the conf.d/30-main commit (which I also have now in dev-wip1).  I did try to remove that (so 4 commits now).

Assuming my build now works we may need to clear this to get "dev" able to merge w/ "dev-wip1"

**Comment by l-arnold** [comment] 2015-09-11 20:21
RE: conf.d/30-main  --branch dev-wip1
(RUNNING MAKE)
Running the Build I see these errors.  The First are about  symlink on openerp.init  (the second are about openerp-server.conf which I created)

I believe we are defining the symlink "in reverse" in both situations.

EDIT (Insert next  2 Lines of Console)
 chown -R openerp:openerp /var/lib/odoo
 update-rc.d openerp-server defaults
insserv: can not symlink(../init.d/urandom, ../rc0.d/K02urandom): File exists
insserv: can not symlink(../init.d/umountfs, ../rc0.d/K08umountfs): File exists
insserv: can not symlink(../init.d/hwclock.sh, ../rc0.d/K06hwclock.sh): File exists
insserv: can not symlink(../init.d/halt, ../rc0.d/K10halt): File exists
insserv: can not symlink(../init.d/umountroot, ../rc0.d/K09umountroot): File exists
insserv: can not symlink(../init.d/sendsigs, ../rc0.d/K04sendsigs): File exists
insserv: can not symlink(../init.d/umountnfs.sh, ../rc0.d/K06umountnfs.sh): File exists
insserv: can not symlink(../init.d/motd, ../rc1.d/S02motd): File exists
insserv: can not symlink(../init.d/bootlogs, ../rc1.d/S06bootlogs): File exists
insserv: can not symlink(../init.d/single, ../rc1.d/S07single): File exists
insserv: can not symlink(../init.d/motd, ../rc2.d/S02motd): File exists
insserv: can not symlink(../init.d/bootlogs, ../rc2.d/S06bootlogs): File exists
insserv: can not symlink(../init.d/rmnologin, ../rc2.d/S07rmnologin): File exists
insserv: can not symlink(../init.d/rc.local, ../rc2.d/S07rc.local): File exists
insserv: can not symlink(../init.d/motd, ../rc3.d/S02motd): File exists
insserv: can not symlink(../init.d/bootlogs, ../rc3.d/S06bootlogs): File exists
insserv: can not symlink(../init.d/rmnologin, ../rc3.d/S07rmnologin): File exists
insserv: can not symlink(../init.d/rc.local, ../rc3.d/S07rc.local): File exists
insserv: can not symlink(../init.d/motd, ../rc4.d/S02motd): File exists
insserv: can not symlink(../init.d/bootlogs, ../rc4.d/S06bootlogs): File exists
insserv: can not symlink(../init.d/rmnologin, ../rc4.d/S07rmnologin): File exists
insserv: can not symlink(../init.d/rc.local, ../rc4.d/S07rc.local): File exists
insserv: can not symlink(../init.d/motd, ../rc5.d/S02motd): File exists
insserv: can not symlink(../init.d/bootlogs, ../rc5.d/S06bootlogs): File exists
insserv: can not symlink(../init.d/rmnologin, ../rc5.d/S07rmnologin): File exists
insserv: can not symlink(../init.d/rc.local, ../rc5.d/S07rc.local): File exists
insserv: can not symlink(../init.d/urandom, ../rc6.d/K02urandom): File exists
insserv: can not symlink(../init.d/umountfs, ../rc6.d/K08umountfs): File exists
insserv: can not symlink(../init.d/hwclock.sh, ../rc6.d/K06hwclock.sh): File exists
insserv: can not symlink(../init.d/reboot, ../rc6.d/K10reboot): File exists
insserv: can not symlink(../init.d/umountroot, ../rc6.d/K09umountroot): File exists
insserv: can not symlink(../init.d/sendsigs, ../rc6.d/K04sendsigs): File exists
insserv: can not symlink(../init.d/umountnfs.sh, ../rc6.d/K06umountnfs.sh): File exists
insserv: can not symlink(../init.d/bootmisc.sh, ../rcS.d/S15bootmisc.sh): File exists
 touch /var/log/openerp-server.log
 chown openerp /var/log/openerp-server.log
 touch /var/run/openerp-server.pid
 chown openerp /var/run/openerp-server.pid
 chown -R openerp:openerp /opt/openerp/odoo
 cd /etc/odoo
 ln -s /opt/openerp/odoo/openerp-server.conf openerp-server.conf
ln: failed to create symbolic link 'openerp-server.conf': File exists
/usr/share/fab/product.mk:476: recipe for target 'build/stamps/root.patched' failed
make: **\* [build/stamps/root.patched] Error 1
root@tkldev products/dev-wip1# ^C

**Comment by l-arnold** [comment] 2015-09-11 20:27
Conf.d/30-main
Lines 73-86 are what we need to fix.
THOUGHTS ON THIS?
- update-rc.d openerp-server defaults

it appears that Jeremy removed the ln -s Code for openerp.init that I was modeling after in this Change:  https://github.com/l-arnold/tkl-nomadic-odoo/commit/1ad08da461cb96203896459470c8a6e8e1cadb2c

However, I added and seems I should remove the following in lines 73-86

 make softlink for openerp.server.conf
cd /etc/odoo
ln -s $OPENERP_DIR/odoo/openerp-server.conf openerp-server.conf
touch openerp-server.conf
chown openerp openerp-server.conf
cd $OPENERP_DIR/odoo/openerp-server.conf
touch openerp-server.conf
chown openerp openerp-server.conf

**Comment by l-arnold** [comment] 2015-09-11 20:58
(EDITED)  New Build Running - now  (waiting for results still).  Reversed the symlinks above + added openerp.init in as well. (reversing deletion around openerp.init (and modifying direction) https://github.com/l-arnold/tkl-nomadic-odoo/commit/1ad08da461cb96203896459470c8a6e8e1cadb2c_

**Comment by l-arnold** [comment] 2015-09-11 21:11
Nope:  Same error but stopped sooner.  Here is the command line.

Jeremy's script did complete from his branch.  I did not watch for errors.

This is TKLDEV processing 30-main (below)
- git clone https://github.com/odoo/odoo.git --branch 8.0 --depth=1 /opt/openerp/odoo
  Cloning into '/opt/openerp/odoo'...
  remote: Counting objects: 21382, done.
  remote: Compressing objects: 100% (17812/17812), done.
  remote: Total 21382 (delta 5487), reused 12306 (delta 2916), pack-reused 0
  Receiving objects: 100% (21382/21382), 102.93 MiB | 1.92 MiB/s, done.
  Resolving deltas: 100% (5487/5487), done.
  Checking connectivity... done.
  Checking out files: 100% (19782/19782), done.
- sed -i s|admin_passwd =.*|admin_passwd = 2b384bd4b9fed21f1378bb0a6bcf2ac1| /etc/odoo/openerp-server.conf
- mkdir /var/lib/odoo
- chown -R openerp:openerp /var/lib/odoo
- update-rc.d openerp-server defaults
  insserv: can not symlink(../init.d/urandom, ../rc0.d/K02urandom): File exists
  insserv: can not symlink(../init.d/umountfs, ../rc0.d/K08umountfs): File exists
  insserv: can not symlink(../init.d/hwclock.sh, ../rc0.d/K06hwclock.sh): File exists
  insserv: can not symlink(../init.d/halt, ../rc0.d/K10halt): File exists
  insserv: can not symlink(../init.d/umountroot, ../rc0.d/K09umountroot): File exists
  insserv: can not symlink(../init.d/sendsigs, ../rc0.d/K04sendsigs): File exists
  insserv: can not symlink(../init.d/umountnfs.sh, ../rc0.d/K06umountnfs.sh): File exists
  insserv: can not symlink(../init.d/motd, ../rc1.d/S02motd): File exists
  insserv: can not symlink(../init.d/bootlogs, ../rc1.d/S06bootlogs): File exists
  insserv: can not symlink(../init.d/single, ../rc1.d/S07single): File exists
  insserv: can not symlink(../init.d/motd, ../rc2.d/S02motd): File exists
  insserv: can not symlink(../init.d/bootlogs, ../rc2.d/S06bootlogs): File exists
  insserv: can not symlink(../init.d/rmnologin, ../rc2.d/S07rmnologin): File exists
  insserv: can not symlink(../init.d/rc.local, ../rc2.d/S07rc.local): File exists
  insserv: can not symlink(../init.d/motd, ../rc3.d/S02motd): File exists
  insserv: can not symlink(../init.d/bootlogs, ../rc3.d/S06bootlogs): File exists
  insserv: can not symlink(../init.d/rmnologin, ../rc3.d/S07rmnologin): File exists
  insserv: can not symlink(../init.d/rc.local, ../rc3.d/S07rc.local): File exists
  insserv: can not symlink(../init.d/motd, ../rc4.d/S02motd): File exists
  insserv: can not symlink(../init.d/bootlogs, ../rc4.d/S06bootlogs): File exists
  insserv: can not symlink(../init.d/rmnologin, ../rc4.d/S07rmnologin): File exists
  insserv: can not symlink(../init.d/rc.local, ../rc4.d/S07rc.local): File exists
  insserv: can not symlink(../init.d/motd, ../rc5.d/S02motd): File exists
  insserv: can not symlink(../init.d/bootlogs, ../rc5.d/S06bootlogs): File exists
  insserv: can not symlink(../init.d/rmnologin, ../rc5.d/S07rmnologin): File exists
  insserv: can not symlink(../init.d/rc.local, ../rc5.d/S07rc.local): File exists
  insserv: can not symlink(../init.d/urandom, ../rc6.d/K02urandom): File exists
  insserv: can not symlink(../init.d/umountfs, ../rc6.d/K08umountfs): File exists
  insserv: can not symlink(../init.d/hwclock.sh, ../rc6.d/K06hwclock.sh): File exists
  insserv: can not symlink(../init.d/reboot, ../rc6.d/K10reboot): File exists
  insserv: can not symlink(../init.d/umountroot, ../rc6.d/K09umountroot): File exists
  insserv: can not symlink(../init.d/sendsigs, ../rc6.d/K04sendsigs): File exists
  insserv: can not symlink(../init.d/umountnfs.sh, ../rc6.d/K06umountnfs.sh): File exists
  insserv: can not symlink(../init.d/bootmisc.sh, ../rcS.d/S15bootmisc.sh): File exists
- -cd /opt/openerp
  tmp/chroot-script.J5eMuo/30_main: 73: tmp/chroot-script.J5eMuo/30_main: -cd: not found
  /usr/share/fab/product.mk:476: recipe for target 'build/stamps/root.patched' failed
  make: **\* [build/stamps/root.patched] Error 127
  root@tkldev products/dev-wip1#

**Comment by l-arnold** [comment] 2015-09-11 21:22
I will remove the SymLinks inserted  (visible here)

![landis-odoo](https://cloud.githubusercontent.com/assets/5673448/9826610/e66d0772-5898-11e5-8df4-41b088378bf8.jpg)

**Comment by l-arnold** [comment] 2015-09-11 22:03
Commented out.  Looks like it is building.  I think the errors that "System moves Past" are because Odoo wants a "temp directory build".  That said, it might not matter.

Ownership may indeed be all that is required.  Thanks @DocCyblade

**Comment by l-arnold** [comment] 2015-09-11 23:54
OK.  It seems to work.  (branch dev-wip1)
Thanks to both of you @DocCyblade @JedMeister 
Password changed from within Odoo.

I added a short "chown" set and commented out about the symlinks.

30-main

Lines 79-83
"#" Change Ownership Landis
touch /etc/odoo/openerp-server.conf
chown openerp /etc/odoo/openerp-server.conf
touch /etc/init.d/openerp-server
chown openerp /etc/init.d/openerp-server

Will be on the road for a few hours now.

Could one of you look at how to merge?

Looks like "dev-notes" should go with DEV branch.
Not quite clear on the merge issue in 30-main (looks like maybe a - (dash) somewhere)

Or when I land I will study Jeremy's not from last "not auto merge" fix.

best to both of you.
Landis

**Comment by JedMeister** [comment] 2015-09-12 01:05
You can remove the `touch` lines as the files already exist in the overlay (it is needed for the log and pid files though because they don't exist). FWIW `touch` makes a new empty file; the same result as `echo > file`.

**Comment by l-arnold** [comment] 2015-09-12 05:09
Got it.  Yeah, the "touch" cam from trying to make the symlinks.. That said I am all ears on tips like yours.

Good call @DocCyblade .  Crazy it took me half day (or more) to put a few test through.

So, if I change some code and want to test again without downloads WHAT DO I DO?
Deck something... then make ?

**Comment by l-arnold** [comment] 2015-09-12 05:09
I think I can close this.  Thanks again guys!

**Closed as completed by l-arnold** 2015-09-12 05:09 UTC
Labels: bug

**Comment by l-arnold** [comment] 2015-09-12 05:53
Branch information (8.0) is passing through install  (to get back to the original question)

**Comment by JedMeister** [comment] 2015-09-13 21:55
A few points:

All this stuff:

> ```
> update-rc.d openerp-server defaults
> insserv: can not symlink(../init.d/urandom, ../rc0.d/K02urandom): File exists
> insserv: can not symlink(../init.d/umountfs, ../rc0.d/K08umountfs): File exists
> insserv: can not symlink(../init.d/hwclock.sh, ../rc0.d/K06hwclock.sh): File exists
> insserv: can not symlink(../init.d/halt, ../rc0.d/K10halt): File exists
> insserv: can not symlink(../init.d/umountroot, ../rc0.d/K09umountroot): File exists
> insserv: can not symlink(../init.d/sendsigs, ../rc0.d/K04sendsigs): File exists
> insserv: can not symlink(../init.d/umountnfs.sh, ../rc0.d/K06umountnfs.sh): File exists
> insserv: can not symlink(../init.d/motd, ../rc1.d/S02motd): File exists
> ```

It's just complaining about that stuff because it is in a chroot. Can be safely ignored... 

These lines:

> ```
> ln -s /opt/openerp/odoo/openerp-server.conf openerp-server.conf
> ln: failed to create symbolic link 'openerp-server.conf': File exists
> ```

This errors because you have your `ln -s` command wrong. Instead of symlinking to a file you are trying to create a symlink over the top of a file (that points to nowhere). FWIW the commits I made move the conf file to /etc/odoo (I moved it in the overlay) so once you updated/merged my commits this line should not error, but it won't do anything either (because the conf file is not longer there...). 

If there is a problem now we have moved the conf; rather than creating random symlinks; we probably should find what is looking for the conf file in the wrong place and fix it!?

Re ownership,
The init script (`/etc/init.d/openerp-server`) should be owned by root (not openerp). IMO the conf file should be either chowned by `openerp:root` (which can be shorhanded to just `openerp` - because it's already owned by `root:root`) or `root:openerp`.

If you change some code and want to rebuild without going through the whole process then in your appliance buide code directory (e.g. /turnkey/fab/products/odoo/) this is how it's done:

```
rm build/stamps/root.patched
make
```

**Comment by l-arnold** [comment] 2015-09-14 01:21
I thought I moved all that out in the end.  Seems it didn't need the symlinks.  Just needed "openerp" owning the files.

perhaps the Dev branch is not working but I think you are seeing an earlier problem.

dev-wip1 is working for me.
Just getting failures on DEV.  Won't even build.  Was going to pull out the few Docs Files I had thrown in there to dev-wp1, then take dev and Demote it.

Did anyone try building DEV besides me?  I tried a merge.  Seemed good but not building after that .
Again branch -- dev-wip1  is working fine.

How does that sound?

**Comment by l-arnold** [comment] 2015-09-14 01:24
On the "already exists"..  I think that was caused by the "touch".
I took out both the touch and they symlink attempt and things started working (perhaps it is still in DEV but I don't think so)

Reality was ownership should have fixed it.

Ran chown openerp-server (and openerp-server.conf) openerp 

Seemed to fix it.  Will look a what it ran for the full build but I expect the rresulting ownership sit is openerp:root
on both files.

**Comment by JedMeister** [comment] 2015-09-14 01:26
I was just working from your comments, not your commits so perhaps it is all resolved? I haven't built anything other than the jed-dev branch (that I issued the PR from). I can have a look later but I have some other stuff I need to get done first.

**Comment by l-arnold** [comment] 2015-09-14 01:38
This is my "dev" branch failure.  Seemed like it was almost done building everything and runs into this on the DEV Branch...  Like I said though dev-wip1 is working well.
- ls /etc/postgresql/
- PGSQL_VER=
- CONF_DIR=/etc/postgresql//main
- pg_dropcluster --stop main
  Usage: /usr/bin/pg_dropcluster [--stop] <version> <cluster>
  /usr/share/fab/product.mk:476: recipe for target 'build/stamps/root.patched' failed
  make: **\* [build/stamps/root.patched] Error 1
